DEFAULT_SYSTEM = 'frontera.tacc.utexas.edu'

API_SAMPLE_DATA = [
    {
        'display_name': 'Stampede3',
        'hostname': 'stampede3.tacc.utexas.edu',
        'resource_type': 'COMPUTE',
        'load_percentage': 86,
        'jobs': {'running': 486, 'queued': 261},
        'online': True,
        'reachable': True,
        'queues_down': False,
        'in_maintenance': False,
        'is_operational': True,
    },
    {
        'display_name': 'Lonestar6',
        'hostname': 'lonestar6.tacc.utexas.edu',
        'resource_type': 'COMPUTE',
        'load_percentage': 99,
        'jobs': {'running': 356, 'queued': 1238},
        'online': True,
        'reachable': True,
        'queues_down': False,
        'in_maintenance': False,
        'is_operational': True,
    },
    {
        'display_name': 'Frontera',
        'hostname': 'frontera.tacc.utexas.edu',
        'resource_type': 'COMPUTE',
        'load_percentage': 92,
        'jobs': {'running': 400, 'queued': 35},
        'online': True,
        'reachable': True,
        'queues_down': False,
        'in_maintenance': False,
        'is_operational': True,
    },
    {
        'display_name': 'Vista',
        'hostname': 'vista.tacc.utexas.edu',
        'resource_type': 'COMPUTE',
        'load_percentage': 100,
        'jobs': {'running': 208, 'queued': 41},
        'online': True,
        'reachable': True,
        'queues_down': False,
        'in_maintenance': False,
        'is_operational': True,
    },
]
